version: '3.9'

services:
  # PostgreSQL
  postgress:
    image: postgres:15
    container_name: postgress
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MongoDB
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Consul
  consul-2:
    image: hashicorp/consul:latest
    container_name: consul-2
    ports:
      - "8500:8500"

  # API Gateway
  apigateway:
    build:
      context: ./apps/ApiGateway
    container_name: apigateway
    ports:
      - "5149:5149"
    depends_on:
      - catalogapi
      - quotation
      - vehicledataintegrator
      - eventbus
      - servicediscovery
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5149
      - SERVICE_DISCOVERY_URL=http://servicediscovery:5198/api/service-registry/services

  # Catalog API
  catalogapi:
    build:
      context: ./apps/CatalogApi
    container_name: catalogapi
    ports:
      - "5189:5189"
    depends_on:
      - postgress
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5189
      - DB_CONNECTION_STRING=Host=postgress;Port=5432;Database=CatalogDb;Username=admin;Password=admin123

  # Quotation API
  quotation:
    build:
      context: ./apps/Quotation
    container_name: quotation
    ports:
      - "5267:5267"
    depends_on:
      - postgress
      - eventbus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5267
      - DB_CONNECTION_STRING=Host=postgress;Port=5432;Database=QuotationDb;Username=admin;Password=admin123
      - EVENT_BUS_URL=http://eventbus:5233/api/events/publish

  # Vehicle Data Integrator
  vehicledataintegrator:
    build:
      context: ./apps/VehicleDataIntegrator
    container_name: vehicledataintegrator
    ports:
      - "5095:5095"
    depends_on:
      - eventbus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5095
      - EVENT_BUS_PUBLISH_URL=http://eventbus:5233/api/events/publish
      - WHEELFITMENT_APIKEY=48eef430773fcf6d915d602d4a6ac541
      - WHEELFITMENT_BASEURL=https://api.wheel-size.com/v2

  # Event Bus
  eventbus:
    build:
      context: ./apps/EventBus
    container_name: eventbus
    ports:
      - "5233:5233"
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5233
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
      - MONGO_DATABASE_NAME=EventBusDatabase
      - MONGO_COLLECTION_NAME=Subscriptions

  # Service Discovery
  servicediscovery:
    build:
      context: ./apps/ServiceDiscovery
    container_name: servicediscovery
    ports:
      - "5198:5198"
    depends_on:
      - consul-2
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5198
      - Consul__Address=http://consul-2:8500

  # Rasa Actions Server
  rasa-actions:
    build:
      context: ./apps/intelligent-assistant/actions
      dockerfile: Dockerfile
    container_name: rasa-actions
    ports:
      - "5055:5055"
    environment:
      - GEMINI_API_KEY=AIzaSyADDl3WEEs_tnpuj03Bmu-kA_n-g4C-lXE
    volumes:
      - ./apps/intelligent-assistant/actions:/app
    restart: always

  # Rasa Server
  rasa:
    build:
      context: ./apps/intelligent-assistant
      dockerfile: Dockerfile
    container_name: rasa
    ports:
      - "5005:5005"
    depends_on:
      - rasa-actions
    environment:
      - RASA_ACTIONS_ENDPOINT=http://rasa-actions:5055/webhook
    volumes:
      - ./apps/intelligent-assistant:/app
      - ./apps/intelligent-assistant/models:/app/models
    restart: always
    command: ["rasa", "run", "--enable-api", "--cors", "*", "--interface", "0.0.0.0", "--endpoints", "endpoints.yml", "--port", "5005"]

volumes:
  postgres_data:
  mongo_data:
